Repository googleapis/gapic-generator-python, pull requests merged in 2021-09, with the labels that each got.

#988 fix: add a separate DEFAULT_CLIENT_INFO for rest clients
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: kokoro:force-run, cla: yes

#989 chore: make conventional commits optional
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#993 feat: Support alternative http bindings in the gapic schema.
  gapic/schema/wrappers.py
  tests/unit/schema/wrappers/test_method.py
Labels: cla: yes

#970 fix: improper types in pagers generation
  gapic/templates/%namespace/%name_%version/%sub/services/%service/pagers.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/pagers.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/pagers.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/pagers.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/pagers.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/pagers.py
Labels: cla: yes

#1000 feat: enable self signed jwt for http
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
Labels: cla: yes

#999 feat: implement grpc transcode for rest transport and complete generated tests
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/utils/__init__.py
  gapic/utils/uri_sample.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/unit/schema/wrappers/test_method.py
Labels: cla: yes
