Repository googleapis/gapic-generator-python, pull requests merged in 2021-05, with the labels that each got.

#855 perf: reduce unnecessary copies, optimize Address comparison
  gapic/ads-templates/%namespace/%name/%version/%sub/__init__.py.j2
  gapic/ads-templates/%namespace/%name/%version/__init__.py.j2
  gapic/ads-templates/%namespace/%name/__init__.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/test_module_import.py.j2
  gapic/generator/generator.py
  gapic/schema/metadata.py
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/__init__.py.j2
  tests/unit/schema/test_metadata.py
  tests/unit/schema/wrappers/test_message.py
Labels: automerge, cla: yes, kokoro:force-run

#845 feat: add autogenerated snippets
  .github/snippet-bot.yml
  .github/workflows/tests.yaml
  .gitignore
  gapic/generator/generator.py
  gapic/samplegen/samplegen.py
  gapic/samplegen_utils/types.py
  gapic/samplegen_utils/utils.py
  gapic/schema/wrappers.py
  gapic/templates/_base.py.j2
  gapic/templates/docs/%name_%version/services.rst.j2
  gapic/templates/examples/feature_fragments.j2
  gapic/templates/examples/sample.py.j2
  gapic/templates/noxfile.py.j2
  gapic/utils/options.py
  noxfile.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_list_resources_grpc.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_method_bidi_streaming_grpc.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_method_lro_signatures_grpc.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_method_one_signature_grpc.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_method_server_streaming_grpc.py
  tests/snippetgen/snippets.proto
  tests/snippetgen/test_snippetgen.py
  tests/unit/generator/test_generator.py
  tests/unit/samplegen/common_types.py
  tests/unit/samplegen/golden_snippets/sample_basic.py
  tests/unit/samplegen/golden_snippets/sample_basic_unflattenable.py
  tests/unit/samplegen/test_integration.py
  tests/unit/samplegen/test_samplegen.py
  tests/unit/samplegen/test_template.py
Labels: cla: yes

#859 fix: add async client to `%name_%version/__init__.py`
  gapic/templates/%namespace/%name_%version/%sub/__init__.py.j2
Labels: cla: yes

#863 fix: remove extra space before_pb_options
  gapic/ads-templates/%namespace/%name/%version/%sub/types/_enum.py.j2
  gapic/templates/%namespace/%name_%version/%sub/types/_enum.py.j2
Labels: cla: yes

#866 feat: Support field presence for query parameters in REST clients
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  repositories.bzl
Labels: cla: yes

#869 fix: also add the async client to __all__
  gapic/templates/%namespace/%name_%version/%sub/__init__.py.j2
  gapic/templates/examples/feature_fragments.j2
Labels: cla: yes

#874 style: update Python client library templates to align with the Python Style Guide
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/pagers.py.j2
Labels: cla: yes

#880 chore: satiate mypy
  gapic/generator/generator.py
Labels: automerge, cla: yes

#873 fix: fix incorrectly referenced exceptions, add missing port to tests
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
Labels: automerge, cla: yes

#883 fix: consistently use _pb2 identifier
  gapic/schema/metadata.py
  tests/unit/schema/test_metadata.py
Labels: automerge, cla: yes

#875 feat: support protobuf method deprecation option [gapic-generator-python]
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  test_utils/test_utils.py
  tests/unit/schema/wrappers/test_method.py
Labels: automerge, cla: yes

#893 fix: remove support for google-api-core<1.26.0
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
Labels: cla: yes

#891 feat: Raise GoogleAPICallError on REST response errors
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: cla: yes

#898 fix: fix datetime comparison unit tests
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
Labels: automerge, cla: yes

#888 feat: Add `x-goog-api-client` header to rest clients
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/setup.py.j2
Labels: cla: yes

#876 docs: Add DEVELOPMENT.md [gapic-generator-python]
  DEVELOPMENT.md
Labels: cla: yes

#907 chore: Add Bazel files to .gitignore [gapic-generator-python]
  .gitignore
Labels: cla: yes

#908 feat(dev): Add Git pre-commit hooks [gapic-generator-python]
  .githooks/pre-commit
  DEVELOPMENT.md
Labels: cla: yes
