Repository googleapis/gapic-generator-python, pull requests merged in 2022-02, with the labels that each got.

#1192 ci: run blacken and lint sessions on generated samples
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
  gapic/templates/.flake8.j2
  gapic/templates/examples/feature_fragments.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  tests/integration/goldens/asset/.flake8
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/samples/generated_samples/cloudasset_generated_asset_v1_asset_service_delete_feed_async.py
  tests/integration/goldens/asset/samples/generated_samples/cloudasset_generated_asset_v1_asset_service_delete_feed_sync.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/.flake8
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/logging/.flake8
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_bucket_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_bucket_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_exclusion_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_exclusion_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_sink_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_sink_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_view_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_delete_view_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_undelete_bucket_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_config_service_v2_undelete_bucket_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_logging_service_v2_delete_log_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_logging_service_v2_delete_log_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_logging_service_v2_tail_log_entries_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_logging_service_v2_tail_log_entries_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_metrics_service_v2_delete_log_metric_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_generated_logging_v2_metrics_service_v2_delete_log_metric_sync.py
  tests/integration/goldens/logging/samples/generated_samples/snippet_metadata_logging_v2.json
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/.flake8
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/setup.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_method_bidi_streaming_async.py
  tests/snippetgen/goldens/mollusca_generated_mollusca_v1_snippets_method_bidi_streaming_sync.py
  tests/snippetgen/goldens/snippet_metadata_mollusca_v1.json
  tests/unit/samplegen/golden_snippets/sample_basic_void_method.py
Labels: automerge, samples

#1201 fix: HTTP body field messages with enums or recursive fields
  gapic/schema/wrappers.py
  test_utils/test_utils.py
  tests/fragments/test_non_primitive_body.proto
  tests/unit/schema/wrappers/test_field.py
Labels: automerge

#1178 fix: disambiguate field headers whose names are reserved python words
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/unit/schema/wrappers/test_method.py
Labels: automerge

#1020 chore: add tests for python 3.10
  .github/workflows/tests.yaml
  gapic/ads-templates/noxfile.py.j2
  gapic/ads-templates/setup.py.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  noxfile.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/setup.py
Labels: cla: yes

#1219 chore: disable mtls showcase tests
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
Labels: automerge
