Repository googleapis/gapic-generator-python, pull requests merged in 2022-12, with the labels that each got.

#1480 fix: Fix timeout default values
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_mixins.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_client_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/constraints-3.7.txt.j2
  tests/integration/BUILD.bazel
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.7.txt
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/async_client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/testing/constraints-3.7.txt
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/testing/constraints-3.7.txt
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/rest.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/testing/constraints-3.7.txt
  tests/integration/goldens/redis/google/cloud/redis_v1/py.typed
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/testing/constraints-3.7.txt
  tests/unit/schema/wrappers/test_service.py
Labels: size: l

#1484 ci: use hashes in pip install statements in release.sh
  .github/.OwlBot.yaml
  .kokoro/requirements.in
  .kokoro/requirements.txt
  owlbot.py
Labels: size: l

#1506 chore: add configured_snippet module
  gapic/configurable_snippetgen/configured_snippet.py
  gapic/configurable_snippetgen/snippet_config_language_pb2.pyi
  requirements.txt
  setup.py
  tests/unit/configurable_snippetgen/resources/README.md
  tests/unit/configurable_snippetgen/resources/speech/request.desc
  tests/unit/configurable_snippetgen/resources/speech/speech_createCustomClass.json
  tests/unit/configurable_snippetgen/resources/speech/speech_v1_generated_adaptation_create_custom_class_basic_async.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
  tests/unit/configurable_snippetgen/test_resources.py
Labels: size: xl

#1523 chore: add ConfiguredSnippet.filename
  gapic/configurable_snippetgen/configured_snippet.py
  requirements.txt
  setup.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
Labels: size: s

#1540 chore: add sample function parameters, without type annotations
  gapic/configurable_snippetgen/configured_snippet.py
  gapic/configurable_snippetgen/libcst_utils.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
  tests/unit/configurable_snippetgen/test_libcst_utils.py
Labels: samples, size: m

#1546 chore: add service client initialization
  gapic/configurable_snippetgen/configured_snippet.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
Labels: size: m
