Repository googleapis/gapic-generator-python, pull requests merged in 2022-07, with the labels that each got.

#1343 fix: resolve issue where rest test appears in grpc-only client
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: s

#1352 ci: fix ci
  .bazelversion
  WORKSPACE
  repositories.bzl
Labels: size: s

#1363 fix: fix wildcard resource names helper method
  gapic/schema/wrappers.py
  tests/integration/BUILD.bazel
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/unit/schema/wrappers/test_message.py
Labels: size: m

#1362 chore(showcase): Update to Showcase 0.22.0
  noxfile.py
Labels: size: xs

#1344 feat: regenerates pb2 file with new protoc.
  gapic/samplegen_utils/snippet_metadata_pb2.py
Labels: size: l

#1367 chore: resolve sphinx warning in generated clients with mixins
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_mixins.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
Labels: size: m

#1368 test: add async suffix to tests to avoid duplication with sync functions
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
Labels: size: s
