Repository googleapis/gapic-generator-python, pull requests merged in 2022-06, with the labels that each got.

#1335 fix: add missing metadata.
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_mixins.py.j2
  noxfile.py
Labels: size: s

#1331 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: size: m

#1312 feat: adds audience.
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  setup.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/base.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/base.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/grpc.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/grpc_asyncio.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc_asyncio.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l
