Repository googleapis/gapic-generator-python, pull requests merged in 2022-10, with the labels that each got.

#1350 feat: add __version__ in GAPIC clients
  gapic/templates/%namespace/%name/__init__.py.j2
  gapic/templates/%namespace/%name/version.py.j2
  gapic/templates/%namespace/%name_%version/%sub/__init__.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/_default_constraints.j2
  gapic/templates/testing/constraints-3.10.txt.j2
  gapic/templates/testing/constraints-3.11.txt.j2
  gapic/templates/testing/constraints-3.7.txt.j2
  gapic/templates/testing/constraints-3.8.txt.j2
  gapic/templates/testing/constraints-3.9.txt.j2
  tests/integration/goldens/asset/google/cloud/asset/__init__.py
  tests/integration/goldens/asset/google/cloud/asset/version.py
  tests/integration/goldens/asset/google/cloud/asset_v1/__init__.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.10.txt
  tests/integration/goldens/asset/testing/constraints-3.11.txt
  tests/integration/goldens/asset/testing/constraints-3.7.txt
  tests/integration/goldens/asset/testing/constraints-3.8.txt
  tests/integration/goldens/asset/testing/constraints-3.9.txt
  tests/integration/goldens/credentials/google/iam/credentials/__init__.py
  tests/integration/goldens/credentials/google/iam/credentials/version.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/__init__.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/testing/constraints-3.10.txt
  tests/integration/goldens/credentials/testing/constraints-3.11.txt
  tests/integration/goldens/credentials/testing/constraints-3.7.txt
  tests/integration/goldens/credentials/testing/constraints-3.8.txt
  tests/integration/goldens/credentials/testing/constraints-3.9.txt
  tests/integration/goldens/eventarc/google/cloud/eventarc/__init__.py
  tests/integration/goldens/eventarc/google/cloud/eventarc/version.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/__init__.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/testing/constraints-3.10.txt
  tests/integration/goldens/eventarc/testing/constraints-3.11.txt
  tests/integration/goldens/eventarc/testing/constraints-3.7.txt
  tests/integration/goldens/eventarc/testing/constraints-3.8.txt
  tests/integration/goldens/eventarc/testing/constraints-3.9.txt
  tests/integration/goldens/logging/google/cloud/logging/__init__.py
  tests/integration/goldens/logging/google/cloud/logging/version.py
  tests/integration/goldens/logging/google/cloud/logging_v2/__init__.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/testing/constraints-3.10.txt
  tests/integration/goldens/logging/testing/constraints-3.11.txt
  tests/integration/goldens/logging/testing/constraints-3.7.txt
  tests/integration/goldens/logging/testing/constraints-3.8.txt
  tests/integration/goldens/logging/testing/constraints-3.9.txt
  tests/integration/goldens/redis/google/cloud/redis/__init__.py
  tests/integration/goldens/redis/google/cloud/redis/version.py
  tests/integration/goldens/redis/google/cloud/redis_v1/__init__.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/testing/constraints-3.10.txt
  tests/integration/goldens/redis/testing/constraints-3.11.txt
  tests/integration/goldens/redis/testing/constraints-3.7.txt
  tests/integration/goldens/redis/testing/constraints-3.8.txt
  tests/integration/goldens/redis/testing/constraints-3.9.txt
Labels: size: l

#1464 fix: Add supported dict typing for client_options
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
Labels: automerge, size: m

#1472 chore: changed version to gapic_version
  gapic/templates/%namespace/%name/__init__.py.j2
  gapic/templates/%namespace/%name/gapic_version.py.j2
  gapic/templates/%namespace/%name_%version/%sub/__init__.py.j2
  gapic/templates/setup.py.j2
  tests/integration/goldens/asset/google/cloud/asset/__init__.py
  tests/integration/goldens/asset/google/cloud/asset/gapic_version.py
  tests/integration/goldens/asset/google/cloud/asset_v1/__init__.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/google/iam/credentials/__init__.py
  tests/integration/goldens/credentials/google/iam/credentials/gapic_version.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/__init__.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/google/cloud/eventarc/__init__.py
  tests/integration/goldens/eventarc/google/cloud/eventarc/gapic_version.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/__init__.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/google/cloud/logging/__init__.py
  tests/integration/goldens/logging/google/cloud/logging/gapic_version.py
  tests/integration/goldens/logging/google/cloud/logging_v2/__init__.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/google/cloud/redis/__init__.py
  tests/integration/goldens/redis/google/cloud/redis/gapic_version.py
  tests/integration/goldens/redis/google/cloud/redis_v1/__init__.py
  tests/integration/goldens/redis/setup.py
Labels: automerge, size: s

#1475 fix: Detect changed Python files in Git pre-commit hook
  .githooks/pre-commit
Labels: automerge, size: xs

#1479 chore: fix snippet metadata filename and add placeholder library version
  gapic/generator/generator.py
  gapic/samplegen_utils/snippet_index.py
  tests/integration/goldens/asset/samples/generated_samples/snippet_metadata_google.cloud.asset.v1.json
  tests/integration/goldens/credentials/samples/generated_samples/snippet_metadata_google.iam.credentials.v1.json
  tests/integration/goldens/eventarc/samples/generated_samples/snippet_metadata_google.cloud.eventarc.v1.json
  tests/integration/goldens/logging/samples/generated_samples/snippet_metadata_google.logging.v2.json
  tests/integration/goldens/redis/samples/generated_samples/snippet_metadata_google.cloud.redis.v1.json
  tests/unit/generator/test_generator.py
  tests/unit/samplegen/test_snippet_index.py
Labels: size: s
