Repository googleapis/gapic-generator-python, pull requests merged in 2022-09, with the labels that each got.

#1428 fix: Fix remaining REST transport issues
  gapic/schema/metadata.py
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/async_client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/credentials/samples/generated_samples/iamcredentials_v1_generated_iam_credentials_generate_access_token_async.py
  tests/integration/goldens/credentials/samples/generated_samples/iamcredentials_v1_generated_iam_credentials_generate_access_token_sync.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/samples/generated_samples/logging_v2_generated_logging_service_v2_list_log_entries_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_v2_generated_logging_service_v2_list_log_entries_sync.py
  tests/integration/goldens/logging/samples/generated_samples/logging_v2_generated_logging_service_v2_tail_log_entries_async.py
  tests/integration/goldens/logging/samples/generated_samples/logging_v2_generated_logging_service_v2_tail_log_entries_sync.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/setup.py
  tests/unit/schema/wrappers/test_field.py
Labels: size: m

#1433 fix: Fix LRO method test and rest test coverage
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: s

#1378 feat: Implement REST support for MixIns
  gapic/schema/api.py
  gapic/schema/mixins.py
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/unit/schema/test_api.py
  tests/unit/schema/wrappers/test_method.py
Labels: size: l

#1436 fix(rest): Use strict encoding to lowercase query string bools
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/setup.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: size: s

#1437 fix: Fix test generation for `*Value` wrapper classes
  .bazelrc
  WORKSPACE
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: s

#1440 fix: remove grpc only rpcs from rest.py
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: size: xs

#1439 chore(test): update Showcase version; make protoc version an env var
  .github/workflows/tests.yaml
  noxfile.py
  tests/system/test_retry.py
  tests/system/test_unary.py
Labels: size: s

#1447 fix: unit test generation for boolean query prams
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: size: xs

#1451 fix: femove `vars` and `set`from reserved names
  gapic/utils/reserved_names.py
Labels: size: xs

#1453 fix: accept 4.x protobuf for gapic-generator-python
  .github/workflows/tests.yaml
  setup.py
Labels: size: s

#1454 fix: do not generate _flattened() unit tests for client streaming methods
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: size: xs

#1458 fix: fix multiple gapic-generator-python bugs
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_client_macros.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: m
