Repository googleapis/gapic-generator-python, pull requests merged in 2022-11, with the labels that each got.

#1443 fix: snippetgen handling of repeated enum field
  gapic/samplegen/samplegen.py
  tests/unit/samplegen/test_samplegen.py
Labels: size: s

#1487 fix: allow google-cloud-documentai < 3
  gapic/templates/setup.py.j2
Labels: size: xs

#1488 chore: fix docs build
  gapic/templates/docs/%name_%version/types.rst.j2
  tests/integration/goldens/asset/docs/asset_v1/types.rst
  tests/integration/goldens/credentials/docs/credentials_v1/types.rst
  tests/integration/goldens/eventarc/docs/eventarc_v1/types.rst
  tests/integration/goldens/logging/docs/logging_v2/types.rst
  tests/integration/goldens/redis/docs/redis_v1/types.rst
Labels: size: xs

#1486 chore: fix url in templated setup.py
  gapic/templates/setup.py.j2
  tests/integration/goldens/credentials/setup.py
Labels: size: xs

#1483 fix: fix typo in testing/constraints-3.7.txt
  gapic/templates/testing/constraints-3.7.txt.j2
  tests/integration/goldens/asset/testing/constraints-3.7.txt
  tests/integration/goldens/credentials/testing/constraints-3.7.txt
  tests/integration/goldens/eventarc/testing/constraints-3.7.txt
  tests/integration/goldens/logging/testing/constraints-3.7.txt
  tests/integration/goldens/redis/testing/constraints-3.7.txt
Labels: size: s

#1495 fix: snippetgen should call await on the operation coroutine before calling result
  gapic/templates/examples/feature_fragments.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/samples/generated_samples/cloudasset_v1_generated_asset_service_analyze_iam_policy_longrunning_async.py
  tests/integration/goldens/asset/samples/generated_samples/cloudasset_v1_generated_asset_service_export_assets_async.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/samples/generated_samples/eventarc_v1_generated_eventarc_create_trigger_async.py
  tests/integration/goldens/eventarc/samples/generated_samples/eventarc_v1_generated_eventarc_delete_trigger_async.py
  tests/integration/goldens/eventarc/samples/generated_samples/eventarc_v1_generated_eventarc_update_trigger_async.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_create_instance_async.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_delete_instance_async.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_export_instance_async.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_failover_instance_async.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_import_instance_async.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_update_instance_async.py
  tests/integration/goldens/redis/samples/generated_samples/redis_v1_generated_cloud_redis_upgrade_instance_async.py
  tests/snippetgen/goldens/mollusca_v1_generated_snippets_method_lro_signatures_async.py
  tests/unit/samplegen/test_template.py
Labels: size: m
