Repository googleapis/gapic-generator-python, pull requests merged in 2022-08, with the labels that each got.

#1382 chore: add `transport` argument to py_gapic_library rule to make its …
  rules_python_gapic/py_gapic.bzl
Labels: automerge, size: xs, owlbot: run

#1385 feat: Add rest-numeric-enums option
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/utils/options.py
  tests/unit/generator/test_options.py
Labels: size: s, owlbot: run

#1387 fix: Unit test for nested fields in url path
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/schema/wrappers.py
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/unit/schema/wrappers/test_field.py
Labels: size: s

#1389 fix: Fix required fields test for REST transport
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/redis/noxfile.py
Labels: size: s

#1349 Chore: Added document ai to setup.py
  gapic/templates/setup.py.j2
  tests/unit/common_types.py
Labels: size: xs

#1397 fix: fixes bug in a test with explicit_routing
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: automerge: exact, size: xs

#1399 feat: Encode numeric enums parameter with REST requests
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: size: xs

#1403 feat: note that "rest" transport support is beta.
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: size: s

#1405 feat: When requesting numeric enums in responses, also send them in requests
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: size: s, owlbot: run

#1411 feat: Add BUILD rule parameter to allow setting numeric enums
  docs/getting-started/bazel.rst
  rules_python_gapic/py_gapic.bzl
Labels: priority: p1, size: s, owlbot: run

#1414 feat(docker-entrypoint): Add --experimental_allow_proto3_optional
  docker-entrypoint.sh
Labels: size: xs, owlbot: run

#1420 fix: Fix rest test generation for non-primitive values in query params
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: size: s

#1421 fix: Fix REST tests generation for repeated enums
  gapic/schema/wrappers.py
  tests/unit/schema/wrappers/test_field.py
Labels: size: s

#1423 feat: Make REST unit tests support numeric enums
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: size: s
