Repository googleapis/gapic-generator-python, pull requests merged in 2022-05, with the labels that each got.

#1294 ci: update required checks
  .github/sync-repo-settings.yaml
Labels: size: s

#1295 chore: update getting-started doc
  docs/getting-started/local.rst
Labels: size: s

#1297 chore: update setup.py
  setup.py
Labels: size: m

#1291 fix: don't use stale session in rest transport
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
Labels: size: m

#1302 ci: use python 3.8 in docs build
  .github/workflows/tests.yaml
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .repo-metadata.json
  .trampolinerc
  README.rst
  noxfile.py
  owlbot.py
Labels: size: m

#1301 feat: release as stable
  .repo-metadata.json
  README.rst
  setup.py
Labels: size: s

#1306 chore: remove obsolete workflow file
  .github/workflows/pypi-upload.yaml
Labels: size: s

#1320 test: use unittest.mock
  gapic/ads-templates/noxfile.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  noxfile.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/conftest.py
  tests/unit/schema/test_api.py
  tests/unit/utils/test_uri_conv.py
Labels: size: m

#1304 feat: adds LRO mixin.
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_mixins.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/_mixins.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/base.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/grpc.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/schema/api.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/unit/schema/test_api.py
Labels: size: xl
