Repository googleapis/gapic-generator-python, pull requests merged in 2023-03, with the labels that each got.

#1618 fix: ignore_unknown_fields parsing service config
  gapic/schema/api.py
Labels: size: xs

#1596 feat: add generator option proto-plus-dep
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/schema/metadata.py
  gapic/schema/naming.py
  gapic/schema/wrappers.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/_pypi_packages.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/_default_constraints.j2
  gapic/templates/testing/constraints-3.7.txt.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  gapic/utils/options.py
  tests/integration/goldens/asset/setup.py
  tests/unit/generator/test_options.py
  tests/unit/schema/test_api.py
  tests/unit/schema/test_naming.py
Labels: size: l

#1628 docs: fix formatting of request arg in docstring
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_client_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
Labels: size: m

#1575 feat: freezes reserved names list.
  gapic/utils/reserved_names.py
  tests/unit/utils/test_uri_conv.py
Labels: size: m

#1613 fix: fix bug with quote replacement.
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins.py.j2
Labels: size: xs
