Repository googleapis/gapic-generator-python, pull requests merged in 2023-08, with the labels that each got.

#1710 chore: fix whitespace
  tests/unit/generator/test_options.py
Labels: size: xs

#1712 build: include error information when integration test fails
  .github/workflows/tests.yaml
Labels: size: xs

#1715 fix: fix docs build for generated clients
  gapic/ads-templates/docs/_static/custom.css.j2
  gapic/ads-templates/docs/conf.py.j2
  gapic/templates/docs/_static/custom.css.j2
  gapic/templates/docs/conf.py.j2
  gapic/templates/noxfile.py.j2
  tests/integration/goldens/asset/docs/_static/custom.css
  tests/integration/goldens/asset/docs/conf.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/credentials/docs/_static/custom.css
  tests/integration/goldens/credentials/docs/conf.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/eventarc/docs/_static/custom.css
  tests/integration/goldens/eventarc/docs/conf.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/logging/docs/_static/custom.css
  tests/integration/goldens/logging/docs/conf.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/redis/docs/_static/custom.css
  tests/integration/goldens/redis/docs/conf.py
  tests/integration/goldens/redis/noxfile.py
Labels: size: s

#1721 fix: preserve new lines
  gapic/utils/lines.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/types/trigger.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/log_entry.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/logging_metrics.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/unit/utils/test_lines.py
Labels: size: m

#1731 build: upgrade rules_python to 0.24.0
  WORKSPACE
  repositories.bzl
  requirements.in
  requirements.txt
Labels: size: l

#1742 test: add service yaml files to integration
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/base.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/grpc.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/integration/BUILD.bazel
  tests/integration/cloudasset_v1.yaml
  tests/integration/eventarc_v1.yaml
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/base.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc_asyncio.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/integration/iamcredentials_v1.yaml
  tests/integration/logging_v2.yaml
  tests/integration/redis_v1.yaml
Labels: size: xl

#1726 fix: remove duplicate import statement for `google.longrunning.operations_pb2`
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/base.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/grpc.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/base.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc_asyncio.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
Labels: automerge, size: m

#1735 tests: fix ModuleNotFoundError when running py_test
  rules_python_gapic/pytest.py
Labels: automerge, size: s
