Repository googleapis/gapic-generator-python, pull requests merged in 2023-09, with the labels that each got.

#1353 fix: Resolve some Showcase test errors
  tests/system/test_retry.py
  tests/system/test_unary.py
Labels: size: xs

#1740 fix: fix docs build for numbered lists
  gapic/utils/lines.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/types/channel.py
  tests/unit/utils/test_lines.py
Labels: size: m

#1125 fix: Change to Set vs FrozenSet and thread the same set through
  gapic/schema/api.py
  gapic/schema/metadata.py
  gapic/schema/wrappers.py
Labels: automerge: exact, size: m
