Repository googleapis/gapic-generator-python, pull requests merged in 2023-02, with the labels that each got.

#1572 chore: prepare to implement snippetgen for standard call
  gapic/configurable_snippetgen/configured_snippet.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
Labels: kokoro:force-run, size: m

#1584 fix: add compatibility with bazel 6; use protobuf 3.21.12 in bazel build rules
  BUILD.bazel
  repositories.bzl
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
Labels: size: s

#1576 fix: fix install issue for packages without google namespace
  gapic/templates/setup.py.j2
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/setup.py
Labels: size: s

#1582 fix: fix generated unit tests with repeated double
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/fragments/test_repeated_double.proto
Labels: size: m

#1599 fix: fix mypy errors in rest.py
  .github/workflows/tests.yaml
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/types/%proto.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/types/%proto.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/types/iamcredentials.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
Labels: size: m

#1603 fix: fix mypy error with rest interceptors
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: size: xs

#1608 fix: Resolve errors from annotating containers with non-local enums
  gapic/ads-templates/%namespace/%name/%version/%sub/types/%proto.py.j2
  gapic/templates/%namespace/%name_%version/%sub/types/%proto.py.j2
  tests/fragments/google/type/dayofweek.proto
  tests/fragments/test_enum_indexed_types.proto
  tests/fragments/test_enum_indexed_types_nonlocal.proto
  tests/fragments/test_repeated_double.proto
  tests/integration/goldens/asset/google/cloud/asset_v1/types/asset_service.py
  tests/integration/goldens/asset/google/cloud/asset_v1/types/assets.py
  tests/integration/goldens/asset/testing/constraints-3.12.txt
  tests/integration/goldens/credentials/google/iam/credentials_v1/types/common.py
  tests/integration/goldens/credentials/testing/constraints-3.12.txt
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/types/eventarc.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/types/trigger.py
  tests/integration/goldens/eventarc/testing/constraints-3.12.txt
  tests/integration/goldens/logging/google/cloud/logging_v2/types/log_entry.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/logging.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/logging_config.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/logging_metrics.py
  tests/integration/goldens/logging/testing/constraints-3.12.txt
  tests/integration/goldens/redis/google/cloud/redis_v1/types/cloud_redis.py
  tests/integration/goldens/redis/testing/constraints-3.12.txt
Labels: size: m
