Repository googleapis/gapic-generator-python, pull requests merged in 2023-10, with the labels that each got.

#1749 fix: resolve unit test failure caused by differences in protobuf runtimes
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  setup.py
  tests/fragments/google/README.rst
  tests/fragments/test_google_protobuf_type.proto
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#1792 fix: add google-cloud-iam to dependencies
  gapic/templates/_pypi_packages.j2
Labels: size: xs

#1799 fix(revert): partial revert of #1125
  gapic/schema/wrappers.py
Labels: size: xs

#1798 fix: fix regression in REST unit test
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/fragments/test_google_protobuf_type.proto
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#1804 fix: add missing dependencies
  gapic/templates/_pypi_packages.j2
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.10.txt
  tests/integration/goldens/asset/testing/constraints-3.11.txt
  tests/integration/goldens/asset/testing/constraints-3.12.txt
  tests/integration/goldens/asset/testing/constraints-3.7.txt
  tests/integration/goldens/asset/testing/constraints-3.8.txt
  tests/integration/goldens/asset/testing/constraints-3.9.txt
Labels: size: s

#1819 test: Enable service yaml in showcase
  noxfile.py
Labels: size: xs

#1820 test: Add service config to showcase
  noxfile.py
Labels: size: s

#1825 fix: upgrade rules_python to 0.26.0
  WORKSPACE
Labels: size: xs
