Repository googleapis/gapic-generator-python, pull requests merged in 2023-11, with the labels that each got.

#1823 Fix: Implement Async Client to use Async Retry to work as expected
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/system/test_retry.py
Labels: size: l

#1852 feat: Introduce compatibility with native namespace packages
  gapic/templates/setup.py.j2
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/setup.py
Labels: size: s

#1834 Fix: wrap method in async client
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_retry.py
Labels: size: m

#1855 fix: allow pb2 files to be included in the output of py_gapic_assembly_pkg
  rules_python_gapic/py_gapic_pkg.bzl
Labels: size: s

#1816 feat: add support for python 3.12
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
  gapic/ads-templates/noxfile.py.j2
  gapic/ads-templates/setup.py.j2
  gapic/schema/metadata.py
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  noxfile.py
  setup.py
  test_utils/__init__.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/setup.py
Labels: size: m

#1863 fix: bump proto-plus version to 1.22.3
  gapic/ads-templates/setup.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/constraints-3.7.txt.j2
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.7.txt
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/testing/constraints-3.7.txt
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/testing/constraints-3.7.txt
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/testing/constraints-3.7.txt
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/testing/constraints-3.7.txt
Labels: size: s

#1867 chore: update url in setup.py
  gapic/templates/setup.py.j2
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/setup.py
Labels: size: s
