Repository googleapis/gapic-generator-python, pull requests merged in 2023-01, with the labels that each got.

#1548 chore: resolve docstring issue where oneof reference is missing
  gapic/ads-templates/%namespace/%name/%version/%sub/types/_message.py.j2
  gapic/templates/%namespace/%name_%version/%sub/types/_message.py.j2
Labels: size: s

#1553 docs(utils): Fix typos in nth function docstring
  gapic/utils/code.py
Labels: size: xs

#1552 docs(client): Fix typo in get_mtls_endpoint_and_cert_source doc
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/async_client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
Labels: size: s

#1555 feat: add support for python 3.11
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
  gapic/ads-templates/noxfile.py.j2
  gapic/ads-templates/setup.py.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/constraints-3.12.txt.j2
  noxfile.py
  requirements.txt
  setup.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.12.txt
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/testing/constraints-3.12.txt
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/testing/constraints-3.12.txt
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/testing/constraints-3.12.txt
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/testing/constraints-3.12.txt
Labels: size: m

#1468 fix: add context manager return types
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
Labels: automerge: exact, size: s

#1547 chore: add client_options to service client initialization
  gapic/configurable_snippetgen/configured_snippet.py
  gapic/configurable_snippetgen/libcst_utils.py
  tests/unit/configurable_snippetgen/resources/speech/speech_v1_generated_adaptation_create_custom_class_basic_async.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
  tests/unit/configurable_snippetgen/test_libcst_utils.py
Labels: size: m

#1569 ci: attempt to speed up ci
  .github/workflows/tests.yaml
Labels: size: s

#1570 chore: add default description for enums
  gapic/templates/%namespace/%name_%version/%sub/types/_enum.py.j2
Labels: size: xs

#1566 chore: support url schema in api endpoint
  gapic/configurable_snippetgen/configured_snippet.py
  tests/unit/configurable_snippetgen/test_configured_snippet.py
Labels: size: m

#1573 fix: use gapic_version from versioned module
  gapic/templates/%namespace/%name_%version/%sub/__init__.py.j2
  gapic/templates/.coveragerc.j2
  tests/integration/goldens/asset/.coveragerc
  tests/integration/goldens/asset/google/cloud/asset_v1/__init__.py
  tests/integration/goldens/credentials/.coveragerc
  tests/integration/goldens/credentials/google/iam/credentials_v1/__init__.py
  tests/integration/goldens/eventarc/.coveragerc
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/__init__.py
  tests/integration/goldens/logging/.coveragerc
  tests/integration/goldens/logging/google/cloud/logging_v2/__init__.py
  tests/integration/goldens/redis/.coveragerc
  tests/integration/goldens/redis/google/cloud/redis_v1/__init__.py
Labels: size: s
