Repository googleapis/gapic-generator-python, pull requests merged in 2024-12, with the labels that each got.

#2265 feat: add debug log when creating client
  gapic/schema/metadata.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/async_client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/unit/schema/test_metadata.py
Labels: size: l

#2270 feat: add debug log when sending requests via REST
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
Labels: size: xl

#2280 chore: skip logging for streaming rest RPCs
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
Labels: size: xs

#2288 fix(log): preserve dict of rest async response headers
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
Labels: size: s

#2299 feat: Add REST Interceptors to support reading metadata
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2304 build: Use Ubuntu 22.04 for tests that require the use of Python 3.7
  .github/workflows/tests.yaml
Labels: size: s
