Repository googleapis/gapic-generator-python, pull requests merged in 2024-09, with the labels that each got.

#2122 chore: optionally generate async rest and client files
  gapic/generator/generator.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
Labels: size: s

#2130 feat: leverage auth session and implement close method
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_base.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest_base.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest_base.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest_base.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_base.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2138 chore: refactor unimplemented method test macro
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2139 feat: wrap async rest methods with retry and error logic
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
Labels: size: m

#2140 feat: add async rest transport call methods
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2141 chore: refactor rest transport bad request test macro
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2126 chore: refactor empty_call_test
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2144 chore: refactor rest call success test macro
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2163 chore: add failsafe check for gRPC
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
Labels: size: s

#2131 test: improve routing parameter assert
  gapic/schema/wrappers.py
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/unit/schema/wrappers/test_routing.py
Labels: size: m

#2145 feat: implement a basic async rest method
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2172 chore: update auth import error statement
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_base.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_universe_domain.py
Labels: size: m

#2133 fix: resolve issue where explicit routing metadata was not sent in async clients
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_client_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2185 chore: update dependencies
  requirements.txt
Labels: size: s

#2176 chore: update auth version in showcase tests
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: m

#2146 feat: add support for async rest streaming methods
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_streams.py
Labels: size: m

#2149 chore: refactor rest interceptor class into jinja macro
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
Labels: size: m

#2151 feat: implement async rest interceptor class
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/__init__.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/__init__.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2178 chore: refactor bad request mixins test
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2179 chore: refactor success call mixins test
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2180 chore: refactor mixins call method
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
Labels: size: m

#2184 chore: sync ads templates
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_shared_macros.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/_rest_mixins.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/_rest_mixins_base.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/rest_base.py.j2
  gapic/ads-templates/%namespace/%name/%version/__init__.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
Labels: size: l, process: review requested

#2186 chore: pre-compute wrappers for mixins
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_mixins.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_shared_macros.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/_rest_mixins_base.py.j2
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins_base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/base.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest_base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest_base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_base.py
Labels: size: l, process: review requested

#2181 feat: implement async rest mixin methods
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_async_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc_asyncio.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_retry.py
Labels: size: xl

#2175 test: add showcase tests for mixins
  tests/system/test_lro.py
  tests/system/test_mixins.py
Labels: size: m

#2194 feat: implement async rest pager methods
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_pagination.py
  tests/system/test_resource_crud.py
Labels: size: xl

#2195 chore: add `async_rest` extra for async rest dependencies
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l
