Repository googleapis/gapic-generator-python, pull requests merged in 2024-10, with the labels that each got.

#2205 fix: add support for field with name 'self'
  gapic/utils/reserved_names.py
  tests/fragments/test_reserved_field_name.proto
Labels: size: xs

#2192 feat: implement async rest lro methods
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  noxfile.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_lro.py
Labels: size: xl

#2210 chore: update api-core version in async extra
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  gapic/templates/setup.py.j2
  noxfile.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/setup.py
Labels: size: s

#2165 test: add routing parameter and empty call test for REST
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2204 fix: streaming for sync REST API calls
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
Labels: size: s

#2212 fix: add default library settings for incorrect lib version
  gapic/schema/api.py
  tests/unit/schema/test_api.py
Labels: size: s

#2217 fix: use disambiguated name for rpcs to avoid collisions
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/client.py.j2
  gapic/ads-templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/fragments/test_reserved_method_names.proto
Labels: size: m

#2218 fix: resolve issue with wait operation mixin
  gapic/ads-templates/%namespace/%name/%version/%sub/services/%service/transports/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_mixins.py.j2
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_base.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/integration/redis_v1.yaml
Labels: size: l

#2219 build: add asyncio to requirements.txt
  requirements.in
  requirements.txt
  rules_python_gapic/py_gapic.bzl
Labels: size: l

#2220 chore: update templated files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/requirements.txt
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/requirements.txt
  owlbot.py
Labels: size: l

#2224 build: add presubmits for unit tests in golden files
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
Labels: size: s

#2225 tests: Add required checks for showcase `_w_rest_async`
  .github/sync-repo-settings.yaml
Labels: size: xs

#2226 fix: allow `google-cloud-kms` 3.x
  gapic/templates/_pypi_packages.j2
Labels: size: xs

#2228 chore: update rest version in client info
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_asyncio.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
Labels: size: s

#2215 feat: Add support for Python 3.13
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
  gapic/ads-templates/noxfile.py.j2
  gapic/ads-templates/setup.py.j2
  gapic/samplegen/samplegen.py
  gapic/templates/noxfile.py.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/constraints-3.13.txt.j2
  noxfile.py
  setup.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.13.txt
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/testing/constraints-3.13.txt
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/testing/constraints-3.13.txt
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/testing/constraints-3.13.txt
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/testing/constraints-3.13.txt
Labels: size: m

#2237 fix: allow google-cloud-documentai 3.x
  gapic/templates/_pypi_packages.j2
Labels: size: xs

#2235 build: release script update
  .github/.OwlBot.lock.yaml
  .kokoro/docs/common.cfg
  .kokoro/release.sh
  .kokoro/release/common.cfg
Labels: size: s

#2236 fix: disable universe-domain validation
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/test_universe_domain.py
Labels: size: l
