Repository googleapis/gapic-generator-python, pull requests merged in 2024-08, with the labels that each got.

#2088 fix: mypy types in get_transport
  gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/async_client.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
Labels: size: s

#2092 build: fix mypy
  gapic/templates/noxfile.py.j2
  noxfile.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/redis/noxfile.py
Labels: size: s

#2085 chore: fix mock runtime warnings
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: xl

#2105 feat: leverage async anonymous credentials in tests
  gapic/templates/tests/unit/gapic/%name_%version/%sub/_test_mixins.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
  tests/system/conftest.py
Labels: size: xl

#2109 build: update googleapis-common-protos
  requirements.txt
Labels: size: xs

#2099 cleanup: refactor rest transport class in gapics
  gapic/generator/generator.py
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/README.rst.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/_rest_mixins_base.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/rest_base.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/README.rst
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/rest_base.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/README.rst
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/rest_base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/README.rst
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/rest_base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/README.rst
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/README.rst
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/README.rst
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/README.rst
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_base.py
  tests/unit/generator/test_generator.py
Labels: size: xl

#2101 process: move assertion outside of `pytest.raises` context in showcase tests
  tests/system/test_error_details.py
  tests/system/test_unary.py
Labels: size: m

#2110 cleanup: refactor empty call test macro
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_macros.j2
  tests/integration/goldens/asset/tests/unit/gapic/asset_v1/test_asset_service.py
  tests/integration/goldens/credentials/tests/unit/gapic/credentials_v1/test_iam_credentials.py
  tests/integration/goldens/eventarc/tests/unit/gapic/eventarc_v1/test_eventarc.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/integration/goldens/logging/tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/integration/goldens/redis/tests/unit/gapic/redis_v1/test_cloud_redis.py
Labels: size: l

#2113 chore: Update response method macro to support async calls
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
Labels: size: xs

#2114 chore: support async in rest call common macro
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
Labels: size: s

#2120 chore: add default library settings
  gapic/schema/api.py
  tests/unit/schema/test_api.py
Labels: size: s
