Repository googleapis/gapic-generator-python, pull requests merged in 2025-03, with the labels that each got.

#2347 fix: resolve issue where pre-release versions of dependencies are installed
  gapic/ads-templates/setup.py.j2
  gapic/templates/_pypi_packages.j2
  gapic/templates/setup.py.j2
  gapic/templates/testing/constraints-3.7.txt.j2
  setup.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/asset/testing/constraints-3.7.txt
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/credentials/testing/constraints-3.7.txt
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/eventarc/testing/constraints-3.7.txt
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging/testing/constraints-3.7.txt
  tests/integration/goldens/logging_internal/setup.py
  tests/integration/goldens/logging_internal/testing/constraints-3.7.txt
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis/testing/constraints-3.7.txt
  tests/integration/goldens/redis_selective/setup.py
  tests/integration/goldens/redis_selective/testing/constraints-3.7.txt
Labels: size: m

#2352 fix: allow Protobuf 6.x
  gapic/templates/setup.py.j2
  setup.py
  tests/integration/goldens/asset/setup.py
  tests/integration/goldens/credentials/setup.py
  tests/integration/goldens/eventarc/setup.py
  tests/integration/goldens/logging/setup.py
  tests/integration/goldens/logging_internal/setup.py
  tests/integration/goldens/redis/setup.py
  tests/integration/goldens/redis_selective/setup.py
Labels: size: s

#2356 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
Labels: size: l

#2346 chore: fix docs link in README
  README.rst
Labels: size: xs

#2343 build: clean up generated noxfile
  gapic/templates/noxfile.py.j2
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging_internal/noxfile.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis_selective/noxfile.py
Labels: size: m

#2362 build: update constraints file to test latest major versions
  gapic/templates/setup.py.j2
  gapic/templates/testing/_default_constraints.j2
  gapic/templates/testing/constraints-3.13.txt.j2
  gapic/templates/testing/constraints-3.7.txt.j2
  tests/integration/goldens/asset/testing/constraints-3.13.txt
  tests/integration/goldens/credentials/testing/constraints-3.13.txt
  tests/integration/goldens/eventarc/testing/constraints-3.13.txt
  tests/integration/goldens/logging/testing/constraints-3.13.txt
  tests/integration/goldens/logging_internal/testing/constraints-3.13.txt
  tests/integration/goldens/redis/testing/constraints-3.13.txt
  tests/integration/goldens/redis_selective/testing/constraints-3.13.txt
Labels: size: m

#2051 fix: missing DEFAULT_HOST should still result in compiling code
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/base.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/base.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/base.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/base.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/base.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/config_service_v2/transports/base.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/logging_service_v2/transports/base.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/metrics_service_v2/transports/base.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/base.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/transports/base.py
Labels: size: s

#2370 build: remove showcase integration tests ads
  .github/sync-repo-settings.yaml
  .github/workflows/tests.yaml
  noxfile.py
Labels: size: s

#2300 tests: add showcase tests for reading grpc/rest response metadata
  tests/system/conftest.py
  tests/system/test_grpc_interceptor_streams.py
  tests/system/test_response_metadata.py
Labels: size: l

#2373 refactor: reduce code duplication
  gapic/templates/%namespace/%name_%version/%sub/services/%service/_shared_macros.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc.py.j2
  gapic/templates/%namespace/%name_%version/%sub/services/%service/transports/grpc_asyncio.py.j2
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc.py
  tests/integration/goldens/credentials/google/iam/credentials_v1/services/iam_credentials/transports/grpc.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/transports/grpc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/config_service_v2/transports/grpc.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/logging_service_v2/transports/grpc.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/metrics_service_v2/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
Labels: size: m
