Repository googleapis/gapic-generator-python, pull requests merged in 2025-08, with the labels that each got.

#2429 fix: Temporarily disable `test_<service>_api_version_header_async` which is not marked as async
  gapic/templates/noxfile.py.j2
  gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
  noxfile.py
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging_internal/noxfile.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis_selective/noxfile.py
Labels: size: s

#2423 chore: depend on stable version of google.shopping.type
  gapic/templates/_pypi_packages.j2
Labels: size: xs

#2431 chore(main): release 1.25.1
  CHANGELOG.md
  setup.py
Labels: size: xs

#2432 docs: minor formatting improvements
  BUILD.bazel
  repositories.bzl
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/async_client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc.py
  tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/transports/grpc_asyncio.py
  tests/integration/goldens/asset/google/cloud/asset_v1/types/asset_service.py
  tests/integration/goldens/asset/google/cloud/asset_v1/types/assets.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/async_client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/services/eventarc/client.py
  tests/integration/goldens/eventarc/google/cloud/eventarc_v1/types/eventarc.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/log_entry.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/logging.py
  tests/integration/goldens/logging/google/cloud/logging_v2/types/logging_config.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/config_service_v2/async_client.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/config_service_v2/client.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/logging_service_v2/async_client.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/services/logging_service_v2/client.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/types/log_entry.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/types/logging.py
  tests/integration/goldens/logging_internal/google/cloud/logging_v2/types/logging_config.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis/google/cloud/redis_v1/types/cloud_redis.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/async_client.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/client.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/transports/grpc.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/transports/grpc_asyncio.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/transports/rest.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/services/cloud_redis/transports/rest_asyncio.py
  tests/integration/goldens/redis_selective/google/cloud/redis_v1/types/cloud_redis.py
Labels: size: xl

#2433 chore: remove unused protobuf dependency in repositories.bzl
  repositories.bzl
Labels: size: s
