Repository googleapis/gapic-generator-python, pull requests merged in 2025-04, with the labels that each got.

#2372 feat: adds augmented pagination to account for BQ family of APIs
  gapic/schema/wrappers.py
  tests/fragments/test_pagination_max_results_and_wrapper.proto
  tests/unit/schema/wrappers/test_method.py
Labels: size: m

#2376 chore: update generated .flake8 configuration file
  gapic/templates/.flake8.j2
  tests/integration/goldens/asset/.flake8
  tests/integration/goldens/credentials/.flake8
  tests/integration/goldens/eventarc/.flake8
  tests/integration/goldens/logging/.flake8
  tests/integration/goldens/logging_internal/.flake8
  tests/integration/goldens/redis/.flake8
  tests/integration/goldens/redis_selective/.flake8
Labels: size: m

#2377 chore: add LICENSE to generated output
  gapic/templates/LICENSE.j2
  tests/integration/goldens/asset/LICENSE
  tests/integration/goldens/credentials/LICENSE
  tests/integration/goldens/eventarc/LICENSE
  tests/integration/goldens/logging/LICENSE
  tests/integration/goldens/logging_internal/LICENSE
  tests/integration/goldens/redis/LICENSE
  tests/integration/goldens/redis_selective/LICENSE
Labels: size: xl

#2378 chore: update generated MANIFEST.in
  gapic/templates/MANIFEST.in.j2
  tests/integration/goldens/asset/MANIFEST.in
  tests/integration/goldens/credentials/MANIFEST.in
  tests/integration/goldens/eventarc/MANIFEST.in
  tests/integration/goldens/logging/MANIFEST.in
  tests/integration/goldens/logging_internal/MANIFEST.in
  tests/integration/goldens/redis/MANIFEST.in
  tests/integration/goldens/redis_selective/MANIFEST.in
Labels: size: m

#2379 chore: update generated noxfile.py
  gapic/templates/noxfile.py.j2
  tests/integration/goldens/asset/noxfile.py
  tests/integration/goldens/credentials/noxfile.py
  tests/integration/goldens/eventarc/noxfile.py
  tests/integration/goldens/logging/noxfile.py
  tests/integration/goldens/logging_internal/noxfile.py
  tests/integration/goldens/redis/noxfile.py
  tests/integration/goldens/redis_selective/noxfile.py
Labels: size: xl

#2380 chore: update generated noxfile.py to cater for grafeas
  gapic/templates/noxfile.py.j2
Labels: size: s

#2381 chore: update generated docs
  docs/conf.py
  gapic/ads-templates/docs/conf.py.j2
  gapic/templates/docs/_static/custom.css.j2
  gapic/templates/docs/_templates/layout.html.j2
  gapic/templates/docs/conf.py.j2
  gapic/templates/docs/index.rst.j2
  gapic/templates/docs/multiprocessing.rst.j2
  tests/integration/goldens/asset/docs/_static/custom.css
  tests/integration/goldens/asset/docs/_templates/layout.html
  tests/integration/goldens/asset/docs/conf.py
  tests/integration/goldens/asset/docs/index.rst
  tests/integration/goldens/asset/docs/multiprocessing.rst
  tests/integration/goldens/credentials/docs/_static/custom.css
  tests/integration/goldens/credentials/docs/_templates/layout.html
  tests/integration/goldens/credentials/docs/conf.py
  tests/integration/goldens/credentials/docs/index.rst
  tests/integration/goldens/credentials/docs/multiprocessing.rst
  tests/integration/goldens/eventarc/docs/_static/custom.css
  tests/integration/goldens/eventarc/docs/_templates/layout.html
  tests/integration/goldens/eventarc/docs/conf.py
  tests/integration/goldens/eventarc/docs/index.rst
  tests/integration/goldens/eventarc/docs/multiprocessing.rst
  tests/integration/goldens/logging/docs/_static/custom.css
  tests/integration/goldens/logging/docs/_templates/layout.html
  tests/integration/goldens/logging/docs/conf.py
  tests/integration/goldens/logging/docs/index.rst
  tests/integration/goldens/logging/docs/multiprocessing.rst
  tests/integration/goldens/logging_internal/docs/_static/custom.css
  tests/integration/goldens/logging_internal/docs/_templates/layout.html
  tests/integration/goldens/logging_internal/docs/conf.py
  tests/integration/goldens/logging_internal/docs/index.rst
  tests/integration/goldens/logging_internal/docs/multiprocessing.rst
  tests/integration/goldens/redis/docs/_static/custom.css
  tests/integration/goldens/redis/docs/_templates/layout.html
  tests/integration/goldens/redis/docs/conf.py
  tests/integration/goldens/redis/docs/index.rst
  tests/integration/goldens/redis/docs/multiprocessing.rst
  tests/integration/goldens/redis_selective/docs/_static/custom.css
  tests/integration/goldens/redis_selective/docs/_templates/layout.html
  tests/integration/goldens/redis_selective/docs/conf.py
  tests/integration/goldens/redis_selective/docs/index.rst
  tests/integration/goldens/redis_selective/docs/multiprocessing.rst
Labels: size: l
